### ISSUE TITLE
Error: EPERM: operation not permitted, rename...

### ISSUE THREAD

**Issue by andrewsantarin** [catamphetamine/libphonenumber-js#139]
Hi. Windows user here.

I'd like to point out that `npm install` might not work for Windows users right out of the box.
```
Error: EPERM: operation not permitted, rename 'D:\Projects\libphonenumber-js\node_modules\.staging\acorn-47041570' -> 'D:\Projects\libphonenumber-js\node_modules\acorn'
    at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
    at FSReqWrap.oncomplete (fs.js:123:15)

Error: EPERM: operation not permitted, rename 'D:\Projects\libphonenumber-js\node_modules\.staging\acorn-47041570' -> 'D:\Projects\libphonenumber-js\node_modules\acorn'
    at Error (native)
 { Error: EPERM: operation not permitted, rename 'D:\Projects\libphonenumber-js\node_modules\.staging\acorn-47041570' -> 'D:\Projects\libphonenumber-js\node_modules\acorn'
    at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
    at FSReqWrap.oncomplete (fs.js:123:15)

Error: EPERM: operation not permitted, rename 'D:\Projects\libphonenumber-js\node_modules\.staging\acorn-47041570' -> 'D:\Projects\libphonenumber-js\node_modules\acorn'
    at Error (native) parent: 'libphonenumber-js' }

Please try running this command again as root/Administrator.
```

I had to loosen up Windows Defender either by: 

1. [disabling real-time protection](https://github.com/react-community/create-react-native-app/issues/191#issuecomment-304073970)
2. [creating a folder exclusion](https://github.com/react-community/create-react-native-app/issues/191#issuecomment-331651305)

There is, of course, third-party antivirus protection, but yeah, I hope this finding helps the next guy running on Windows.

**Comment by catamphetamine** [comment]
Seems like something related to installing `acorn` package.
I don't think it's something unique to this library.
Anyway, thx.
