### ISSUE TITLE
isValidNumberCustom is undefined

### ISSUE THREAD

**Issue by iamvanja** [catamphetamine/libphonenumber-js#99]
`import { isValidNumberCustom } from 'libphonenumber-js'`
`isValidNumberCustom` is `undefined`

`import { isValidNumber as isValidNumberCustom } from 'libphonenumber-js/custom'`
`typeof isValidNumberCustom // function`

Env:
Node v8.1.2
Babel 6.24.0

**Comment by catamphetamine** [comment]
Perhaps your bundler is not reading `index.es6.js` but rather `index.common.js`.
Try manually: from `libphonenumber-js/index.es6`

**Comment by iamvanja** [comment]
`import { isValidNumberCustom } from 'libphonenumber-js/index.es6'`

results in

```js
[0]   stack:
[0]    [ '/Users/vanja/Sites/smart-clinic/v5/integration-server/node_modules/libphonenumber-js/index.es6.js:1',
[0]      '(function (exports, require, module, __filename, __dirname) { import metadata from \'./metadata.min.json\'',
[0]      '                                                              ^^^^^^',
[0]      '',
[0]      'SyntaxError: Unexpected token import',
[0]      '    at createScript (vm.js:74:10)',
[0]      '    at Object.runInThisContext (vm.js:116:10)',
[0]      '    at Module._compile (module.js:533:28)',
[0]      '    at Module._extensions..js (module.js:580:10)',
[0]      '    at Object.require.extensions.(anonymous function) [as .js] (/Users/vanja/Sites/smart-clinic/v5/integration-server/node_modules/babel-register/lib/node.js:152:7)',
[0]      '    at Module.load (module.js:503:32)',
[0]      '    at tryModuleLoad (module.js:466:12)',
[0]      '    at Function.Module._load (module.js:458:3)',
[0]      '    at Module.require (module.js:513:17)',
[0]      '    at require (internal/module.js:11:18)' ] }
```

My metadata file is not in root.
Just wanted you to be aware of this, not sure if it is a wide spread problem.

**Comment by catamphetamine** [comment]
What bundler are you using?

Try it ES5 way:

```js
import { isValidNumber } from 'libphonenumber-js/custom'
```

https://github.com/catamphetamine/libphonenumber-js/blob/master/custom.js
